### PR TITLE
Update to CircleCI 2

### PR DESCRIPTION
**Pull request by ardunn**
update to circleci 2.0

### CODE REVIEW

**Comment by computron** [comment]
Is this ready to merge?

**Comment by ardunn** [comment]
@computron Not yet! Will remove WIP tag when it is

**Comment by ardunn** [comment]
Ok I think it is ready to merge as both 3.6 and 2.7 tests run and pass, although it seems like a lot of tracebacks are being std-outed, although this may be intentional as part of error-testing?
@computron

**Comment by computron** [comment]
Thanks! there's often a lot of stdout

**Pull request merged**
