### PR TITLE
a utility script to update files path in any collection of the database

### PR DESCRIPTION
**Pull request by albalu**
a function and a unittest for updating the path of the files (or basically any string) inside a collection.

### CODE REVIEW

**Comment by computron** [comment]
@albalu 

1 - make sure the unit tests work. see the message about "All checks have failed" in this PR. You should run unit tests locally before submitting a pull request
2 - add docs
3 - i will likely need to clean this up a bit afterward, but that is no big deal

Thanks!

**Comment by albalu** [comment]
@computron, it seems like tqdm is causing problems. When I click on details I see this in traceback of the errors:

"File "/home/travis/build/materialsproject/fireworks/fireworks/utilities/update_dir_paths.py", line 2, in <module>
    from tqdm import tqdm
ImportError: No module named tqdm"

**Comment by computron** [comment]
You need to add tqdm to setup.py and requirements.txt

**Comment by computron** [comment]
Thanks!

**Pull request merged**
