### PR TITLE
updates

### PR DESCRIPTION
**Pull request by matk86**
*  plot_wf  bug fixes
*  filepad updates: 
* add count method
* add task to insert files that match the given pattern, add unittest, some cleanup

### CODE REVIEW

**Comment by computron** [comment]
Hi @matk86 

Why not add the pattern matching as an option to the default AddFilesTask rather than having a separate task? Might help remove duplicated portions of code as well as keep the feature set (labels, etc) consistent between the two modes.

**Comment by computron** [comment]
(e.g., a flag called "allow_wildcards" or "pattern_match" in the AddFileTask)

**Comment by matk86** [comment]
i considered that option, since paths and labels are required params  for AddFilesTask, one would be forced to set those even though those are not needed when the paths are to be obtained from the given pattern..

**Comment by computron** [comment]
@matk86 that is easily fixable

1 - the "paths" requirement is a complete non-issue. It is the same exact thing as your patterns input. It is just that when you set the use_wildcards flag to true, then paths becomes interpreted as patterns. It's the same exact parameter
2 - as for labels, just make it an optional parameter in all cases. If it's not set, make sure it is the *full* path of the file to try to avoid collisions since the label is supposed to be unique
3 - (optional) probably, we want rename the word "label" to "identifier". The word label sounds like a category and non-unique, whereas this string is supposed to uniquely identify the file.

With these in place you can just have a single FireTask

**Comment by computron** [comment]
Thanks!

**Pull request merged**
