### PR TITLE
warn webgui query about slow queries

### PR DESCRIPTION
**Pull request by dwinston**
If the `FWAPP_PERF_WARNINGS` env var is set, flash a message to the top of the home page after submitting a query that doesn't use an index of the corresponding collection.

Encourages users to e.g. [add to](https://pythonhosted.org/FireWorks/performance_tutorial.html) `user_indices` and `wf_user_indices` in their `my_launchpad.yaml` config file.

### CODE REVIEW

**Comment by computron** [comment]
Thanks!

Can you put the PERF_WARNINGS variable in the fw_config instead of env var?

The only reason we have env vars for username/password in the app is because I couldn't find a better way to communicate this information to the Flask app. But in general, we are trying to move away from environment variables (e.g., how pymatgen removed MAPI_KEY env var, etc).

**Comment by computron** [comment]
@dwinston - see my comments above (just in case using the @ shoutout helps send the message your way)

**Comment by dwinston** [comment]
@computron it's now settable as `perf_warnings: true` line in config YAML.

**Comment by dwinston** [comment]
Okay, now actually using fw_config rather than lpad init (!)

**Comment by computron** [comment]
thanks!

**Pull request merged**
